## CHANGE this to the name of your plugin.
name: MoarRedstone
author: Seggan
description: Adds more redstone stuff based off of Slimefun
main: io.github.seggan.moarredstone.MoarRedstone
version: ${project.version}
api-version: 1.16
depend:
  - Slimefun